### ISSUE TITLE
How to determine the limit of request times？

### ISSUE THREAD

**Issue by gyp719** [moe-mizrak/laravel-openrouter#18]
$limitResponse = LaravelOpenRouter::limitRequest();

<img width="578" alt="image" src="https://github.com/user-attachments/assets/941a323e-0108-4c05-9026-81c0527a0dad">

我应该根据那个参数来判断是否可以继续进行请求？ 正确响应和错误响应反核的结果一致

Should I use that parameter to determine if I can proceed with the request? The correct response and incorrect response result in consistent anti nuclear results

**Comment by moe-mizrak** [comment]
@gyp719 
Well, If I get the question right, limitRequest() does not need any parameter. Your query and response are correct.

For more info about limitRequest, you can also check OpenRouter document:
https://openrouter.ai/docs/limits

As stated in document, query response is for "To check the rate limit or credits left on an API key".

If answer does not answer what you are looking for, please give some more info, I will be able to respond as soon as possible.
